# Autogenerated wrapper script for GAP_pkg_crypting_jll for x86_64-linux-gnu
export crypting

using GAP_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_crypting")
JLLWrappers.@declare_file_product(crypting)
function __init__()
    JLLWrappers.@generate_init_header(GAP_jll)
    JLLWrappers.@init_file_product(
        crypting,
        "lib/gap/crypting.so",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
